language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update && composer --version
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --verbose